INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (1,'LUCA','GODANO', 'LUCA@ACME.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (2,'JOSE LUIS','SANCHEZ', 'JOSETE@ACME.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (3,'YAGO','CRESPO', 'YAGO@ACME.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (4,'BRUNO','GARCIA', 'BRUNO@ACME.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (5,'RAMON','CRESPO', 'RAMON@ACME.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (6,'ESTHER','VALBUENA', 'ESTHER@ACME.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (7,'MISHA','MALIGA', 'MISHA@ACME.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (8,'PATRICIA','PARREIRA', 'PATRICIA@ACME.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (9,'RAFAEL','SALGADO', 'RAFAEL@ACME.ES');