INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (1,'LUCA','GODANO', 'LUCA@VENTURA24.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (2,'JOSE LUIS','SANCHEZ', 'JOSETE@VENTURA24.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (3,'YAGO','CRESPO', 'YAGO@VENTURA24.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (4,'BRUNO','GARCIA', 'BRUNO@VENTURA24.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (5,'RAMON','CRESPO', 'RAMON@VENTURA24.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (6,'ESTHER','VALBUENA', 'ESTHER@VENTURA24.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (7,'MISHA','MALIGA', 'MISHA@VENTURA24.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (8,'PATRICIA','PARREIRA', 'PATRICIA@VENTURA24.ES');
INSERT INTO CUSTOMERS (ID, NAME, SURNAME, EMAIL) VALUES (9,'RAFAEL','SALGADO', 'RAFAEL@VENTURA24.ES');