version: '3'

services:

  cassandra:
    image: cassandra:3
    ports:
      - 9042:9042
      - 9160:9160

  rabbit:
    image: rabbitmq:3.7-management-alpine
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
#    environment:
#    This variable speeds up rabbitMQ runtime, but make it slower to startup
#      - RABBITMQ_HIPE_COMPILE= 1

  gw:
    build: GW
    ports:
      - 9080:8080
    depends_on:
      - rabbit
      - draw
      - customer
      - notification
      - bet
    links:
      - rabbit:queue
      - cassandra:database

  bet:
    build: BetService
    depends_on:
       - rabbit
       - cassandra
    links:
       - rabbit:queue
       - cassandra:database

  customer:
    build: Customer
    depends_on:
       - rabbit
       - cassandra
    links:
       - rabbit:queue
       - cassandra:database

  draw:
    build: DrawService
    depends_on:
      - rabbit
      - cassandra
    links:
      - rabbit:queue
      - cassandra:database

  notification:
    build: NotificationService
    depends_on:
       - rabbit
       - mail-server
    links:
       - rabbit:queue
       - mail-server
       - cassandra:database

  mail-server:
    image: mailhog/mailhog
    ports:
       - 1025:1025
       - 8025:8025
