version: '2'

services:
  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
#    environment:
#    This variable speeds up rabbitMQ runtime, but make it slower to startup
#      - RABBITMQ_HIPE_COMPILE= 1

  gw:
    build: GW
    ports:
      - 9080:8080
    depends_on:
      - rabbit
      - draw
      - customer
      - notification
      - bet
    links:
      - rabbit:queue

  bet:
    build: BetService
    depends_on:
       - rabbit
    links:
       - rabbit:queue

  customer:
    build: Customer
    depends_on:
       - rabbit
    links:
       - rabbit:queue

  draw:
    build: DrawService
    depends_on:
      - rabbit
    links:
      - rabbit:queue

  notification:
    build: NotificationService
    depends_on:
       - rabbit
       - mail-server
    links:
       - rabbit:queue
       - mail-server   
       

  mail-server:
    image: mailhog/mailhog
    ports:
       - 1025:1025
       - 8025:8025
